/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminUsers: () => import('#controllers/admin_users_controller'),
  ConnectedObjects: () => import('#controllers/connected_objects_controller'),
  Flags: () => import('#controllers/flags_controller'),
  Home: () => import('#controllers/home_controller'),
  Incidents: () => import('#controllers/incidents_controller'),
  LiveTiming: () => import('#controllers/live_timing_controller'),
  Networking: () => import('#controllers/networking_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Session: () => import('#controllers/session_controller'),
}
