/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ConnectedObjectSchema extends BaseModel {
  static $columns = ['createdAt', 'firmware', 'id', 'identifier', 'name', 'sector', 'status', 'type', 'updatedAt'] as const
  $columns = ConnectedObjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare firmware: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string
  @column()
  declare name: string
  @column()
  declare sector: string
  @column()
  declare status: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventSchema extends BaseModel {
  static $columns = ['accentColor', 'createdAt', 'displayOrder', 'endDate', 'id', 'startDate', 'status', 'title', 'updatedAt'] as const
  $columns = EventSchema.$columns
  @column()
  declare accentColor: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayOrder: number
  @column.date()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare startDate: DateTime
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FlagSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'sector', 'updatedAt'] as const
  $columns = FlagSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sector: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IncidentSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'sector', 'severity', 'type', 'updatedAt', 'vehicles'] as const
  $columns = IncidentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sector: string
  @column()
  declare severity: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicles: string | null
}

export class TeamSchema extends BaseModel {
  static $columns = ['accentColor', 'carModel', 'category', 'country', 'createdAt', 'description', 'displayOrder', 'id', 'name', 'teamPrincipal', 'updatedAt'] as const
  $columns = TeamSchema.$columns
  @column()
  declare accentColor: string
  @column()
  declare carModel: string
  @column()
  declare category: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare displayOrder: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare teamPrincipal: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarPath', 'birthDate', 'createdAt', 'email', 'followedTeam', 'fullName', 'gender', 'id', 'isVerified', 'jobTitle', 'level', 'password', 'points', 'pseudo', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarPath: string | null
  @column.date()
  declare birthDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare followedTeam: string | null
  @column()
  declare fullName: string | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVerified: boolean
  @column()
  declare jobTitle: string | null
  @column()
  declare level: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare points: number
  @column()
  declare pseudo: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
